version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy-dev
    ports:
      - "${CLIENT_PORT:-3000}:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
    networks:
      - iwc-network-dev
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: iwc-learning-client-dev
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5000}
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    ports:
      - "3000"
    restart: always
    depends_on:
      - server
    networks:
      - iwc-network-dev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: iwc-learning-server-dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-iwc_language_db}
      - PORT=${SERVER_PORT:-5000}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
    ports:
      - "${SERVER_PORT:-5000}:5000"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - iwc-network-dev

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-iwc_language_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - iwc-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  postgres-data-dev:

networks:
  iwc-network-dev:
    driver: bridge